# Generated by Django 5.1.3 on 2025-01-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lector",
            fields=[
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("", "Tria una opció"),
                            ("1", "Josep"),
                            ("2", "Gisela"),
                        ],
                        default="",
                        max_length=1,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "lec_fk",
                    models.SmallAutoField(
                        primary_key=True, serialize=False, verbose_name="id del lector"
                    ),
                ),
                (
                    "lec_nom",
                    models.CharField(max_length=100, verbose_name="lector del llibre"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Propietari",
            fields=[
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("", "Tria una opció"),
                            ("1", "Josep"),
                            ("2", "Gisela"),
                        ],
                        default="",
                        max_length=1,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "prop_fk",
                    models.SmallAutoField(
                        primary_key=True, serialize=False, verbose_name="id propietari"
                    ),
                ),
                (
                    "prop_nom",
                    models.CharField(
                        max_length=100, verbose_name="propietari del llibre"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Llibre",
            fields=[
                (
                    "llib_pk",
                    models.SmallAutoField(
                        primary_key=True, serialize=False, verbose_name="id llibre"
                    ),
                ),
                (
                    "llib_nom",
                    models.CharField(max_length=150, verbose_name="nom del llibre"),
                ),
                (
                    "llib_autor",
                    models.CharField(max_length=100, verbose_name="autor del llibre"),
                ),
                (
                    "llib_editorial",
                    models.CharField(max_length=100, verbose_name="editorial"),
                ),
                (
                    "llib_genere",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Tria una opció"),
                            ("1", "Assaig"),
                            ("2", "Novel·la"),
                            ("3", "Novel·la policíaca"),
                            ("4", "Novel·la romàntica"),
                            ("5", "Novel·la històrica"),
                            ("6", "Novel·la fantàstica"),
                            ("7", "Filosofia"),
                            ("8", "Mitologia"),
                            ("9", "Poesía"),
                            ("10", "Còmic"),
                            ("11", "Història"),
                            ("12", "Art"),
                            ("13", "Biografia"),
                            ("14", "Teatre"),
                        ],
                        max_length=2,
                        verbose_name="génere literari",
                    ),
                ),
                (
                    "llib_pagines",
                    models.IntegerField(verbose_name="número de pàgines del llibre"),
                ),
                ("llib_data_lectura", models.DateField()),
                (
                    "llib_portada",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portadas/",
                        verbose_name="Portada del llibre",
                    ),
                ),
                (
                    "llib_lector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lectures2025.lector",
                        verbose_name="qui ha llegit el llibre",
                    ),
                ),
                (
                    "llib_propietari",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lectures2025.propietari",
                        verbose_name="propietari del llibre",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lector",
            name="llib_nom_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lectures2025.llibre",
                verbose_name="llibres llegits",
            ),
        ),
    ]
